/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class', // Enable dark mode with class strategy
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Primary color scale - references CSS variables for consistency
        primary: {
          DEFAULT: 'var(--color-primary-500)',
          50: 'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
          hover: 'var(--color-primary-hover)',
        },
        // Secondary color scale
        secondary: {
          DEFAULT: 'var(--color-secondary-500)',
          50: 'var(--color-secondary-50)',
          100: 'var(--color-secondary-100)',
          200: 'var(--color-secondary-200)',
          300: 'var(--color-secondary-300)',
          400: 'var(--color-secondary-400)',
          500: 'var(--color-secondary-500)',
          600: 'var(--color-secondary-600)',
          700: 'var(--color-secondary-700)',
          800: 'var(--color-secondary-800)',
          900: 'var(--color-secondary-900)',
          hover: 'var(--color-secondary-hover)',
        },
        // Accent color scale
        accent: {
          DEFAULT: 'var(--color-accent-500)',
          50: 'var(--color-accent-50)',
          100: 'var(--color-accent-100)',
          200: 'var(--color-accent-200)',
          300: 'var(--color-accent-300)',
          400: 'var(--color-accent-400)',
          500: 'var(--color-accent-500)',
          600: 'var(--color-accent-600)',
          700: 'var(--color-accent-700)',
          800: 'var(--color-accent-800)',
          900: 'var(--color-accent-900)',
          hover: 'var(--color-accent-hover)',
        },
        'background-light': '#FFFFFF',
        'background-dark': '#18181b',
        // Gemini Design System Colors
        'gemini': {
          primary: 'var(--color-primary-500)',
          'primary-hover': 'var(--color-primary-600)',
          bg: 'var(--bg)',
          card: 'var(--bg-inset)',
          'text-dark': 'var(--fg)',
          'text-gray': 'var(--fg-muted)',
          'text-muted': 'var(--fg-subtle)',
          border: 'var(--line)',
          success: 'var(--signal-good)',
          warning: 'var(--signal-warn)',
        },
        zinc: {
          50: '#fafafa',
          100: '#f4f4f5',
          200: '#e4e4e7',
          300: '#d4d4d8',
          400: '#a1a1aa',
          500: '#71717a',
          600: '#52525b',
          700: '#3f3f46',
          800: '#27272a',
          900: '#18181b',
        },
        green: {
          50: '#f0fdf4',
          500: '#22c55e',
          600: '#16a34a',
        },
        red: {
          50: '#fef2f2',
          500: '#ef4444',
          600: '#dc2626',
        },
        // Flavor Profile Colors
        flavor: {
          fruity: '#E4572E',
          floral: '#E9A2AD',
          vegetal: '#57A773',
          smoky: '#6B5B95',
          sweet: '#DFAF2B',
          spicy: '#B53F3F',
          bitter: '#2F4858',
          sour: '#3B9ED8',
          roasted: '#8C5A3A',
          nutty: '#C29F6D',
          mineral: '#7A8A8C',
          earthy: '#6D7F4B',
        },
        // Text Colors
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-text-muted)',
        'text-inverse': 'var(--color-text-inverse)',
        // Border Colors
        'border-subtle': 'var(--color-border-subtle)',
        'border-default': 'var(--color-border-default)',
        'border-strong': 'var(--color-border-strong)',
        'border-focus': 'var(--color-border-focus)',
        // Background Colors
        'background-app': 'var(--color-background-app)',
        'background-surface': 'var(--color-background-surface)',
        'background-surface-secondary': 'var(--color-background-surface-secondary)',
        'background-muted': 'var(--color-background-muted)',
        // Semantic Colors
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        error: 'var(--color-error)',
        info: 'var(--color-info)',
      },
      fontFamily: {
        display: ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'xs': ['clamp(0.75rem, 0.7rem + 0.25vw, 0.875rem)', { lineHeight: '1.5' }],
        'sm': ['clamp(0.875rem, 0.8rem + 0.375vw, 1rem)', { lineHeight: '1.5' }],
        'base': ['clamp(1rem, 0.9rem + 0.5vw, 1.125rem)', { lineHeight: '1.6' }],
        'lg': ['clamp(1.125rem, 1rem + 0.625vw, 1.25rem)', { lineHeight: '1.5' }],
        'xl': ['clamp(1.25rem, 1.1rem + 0.75vw, 1.5rem)', { lineHeight: '1.4' }],
        '2xl': ['clamp(1.5rem, 1.3rem + 1vw, 1.875rem)', { lineHeight: '1.3' }],
        '3xl': ['clamp(1.875rem, 1.6rem + 1.375vw, 2.25rem)', { lineHeight: '1.2' }],
        '4xl': ['clamp(2.25rem, 1.9rem + 1.75vw, 3rem)', { lineHeight: '1.1' }],
        '5xl': ['clamp(3rem, 2.5rem + 2.5vw, 3.75rem)', { lineHeight: '1' }],
        '6xl': ['clamp(3.75rem, 3rem + 3.75vw, 4.5rem)', { lineHeight: '1' }],
        'h1': ['clamp(2.25rem, 1.9rem + 1.75vw, 3rem)', { lineHeight: '1.1', fontWeight: '700' }],
        'h2': ['clamp(1.875rem, 1.6rem + 1.375vw, 2.25rem)', { lineHeight: '1.2', fontWeight: '600' }],
        'h3': ['clamp(1.5rem, 1.3rem + 1vw, 1.875rem)', { lineHeight: '1.3', fontWeight: '600' }],
        'h4': ['clamp(1.25rem, 1.1rem + 0.75vw, 1.5rem)', { lineHeight: '1.4', fontWeight: '500' }],
        'h5': ['clamp(1.125rem, 1rem + 0.625vw, 1.25rem)', { lineHeight: '1.5', fontWeight: '500' }],
        'h6': ['clamp(1rem, 0.9rem + 0.5vw, 1.125rem)', { lineHeight: '1.5', fontWeight: '500' }],
        'body': ['clamp(1rem, 0.9rem + 0.5vw, 1.125rem)', { lineHeight: '1.6' }],
        'body-sm': ['clamp(0.875rem, 0.8rem + 0.375vw, 1rem)', { lineHeight: '1.5' }],
        'caption': ['clamp(0.75rem, 0.7rem + 0.25vw, 0.875rem)', { lineHeight: '1.4' }],
      },
      fontWeight: {
        thin: '100',
        extralight: '200',
        light: '300',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
        black: '900',
      },
      lineHeight: {
        none: '1',
        tight: '1.1',
        snug: '1.2',
        normal: '1.3',
        relaxed: '1.4',
        loose: '1.5',
        'extra-loose': '1.6',
        'heading': '1.3',
        'body': '1.6',
      },
      letterSpacing: {
        tighter: '-0.05em',
        tight: '-0.025em',
        normal: '0em',
        wide: '0.025em',
        wider: '0.05em',
        widest: '0.1em',
      },
      spacing: {
        px: '1px',
        0: '0px',
        0.5: '2px',
        1: '4px',
        1.5: '6px',
        2: '8px',
        2.5: '10px',
        3: '12px',
        3.5: '14px',
        4: '16px',
        5: '20px',
        6: '24px',
        7: '28px',
        8: '32px',
        9: '36px',
        10: '40px',
        11: '44px',
        12: '48px',
        14: '56px',
        16: '64px',
        20: '80px',
        24: '96px',
        28: '112px',
        32: '128px',
        36: '144px',
        40: '160px',
        44: '176px',
        48: '192px',
        52: '208px',
        56: '224px',
        60: '240px',
        64: '256px',
        72: '288px',
        80: '320px',
        96: '384px',
        // Responsive spacing with clamp()
        'xs': 'clamp(0.25rem, 0.2rem + 0.25vw, 0.375rem)',
        'sm': 'clamp(0.5rem, 0.4rem + 0.5vw, 0.75rem)',
        'md': 'clamp(0.75rem, 0.6rem + 0.75vw, 1.125rem)',
        'lg': 'clamp(1rem, 0.8rem + 1vw, 1.5rem)',
        'xl': 'clamp(1.5rem, 1.2rem + 1.5vw, 2.25rem)',
        '2xl': 'clamp(2rem, 1.6rem + 2vw, 3rem)',
        '3xl': 'clamp(2.5rem, 2rem + 2.5vw, 3.75rem)',
        '4xl': 'clamp(3rem, 2.4rem + 3vw, 4.5rem)',
      },
      borderRadius: {
        none: '0px',
        sharp: 'var(--r-sharp)',   // 2px  — chips, badges
        soft: 'var(--r-soft)',     // 10px — buttons, inputs
        pane: 'var(--r-pane)',     // 18px — cards, sheets
        full: '9999px',
      },
      maxWidth: {
        none: 'none',
        0: '0rem',
        xs: '20rem',
        sm: '24rem',
        md: '28rem',
        lg: '32rem',
        xl: '36rem',
        '2xl': '42rem',
        '3xl': '48rem',
        '4xl': '56rem',
        '5xl': '64rem',
        '6xl': '72rem',
        '7xl': '80rem',
        full: '100%',
        min: 'min-content',
        max: 'max-content',
        fit: 'fit-content',
        prose: '65ch',
        screen: '100vw',
      },
      boxShadow: {
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'none': '0 0 #0000',
      },
      backgroundImage: {
        // Primary gradients
        'gradient-primary': 'linear-gradient(135deg, #1F5D4C 0%, #2E7D32 100%)',
        'gradient-primary-soft': 'linear-gradient(135deg, #1F5D4C 0%, #1A4A3E 100%)',
        'gradient-accent': 'linear-gradient(135deg, #C65A2E 0%, #D6743A 100%)',
        'gradient-accent-soft': 'linear-gradient(135deg, #C65A2E 0%, #B85027 100%)',
        // New agave gradient
        'gradient-agave': 'linear-gradient(135deg, #1F5D4C 0%, #C65A2E 100%)',
        'gradient-agave-reverse': 'linear-gradient(135deg, #C65A2E 0%, #1F5D4C 100%)',
        // Background gradients
        'gradient-subtle': 'radial-gradient(90% 120% at 0% 0%, #FDF4E6 0%, #F7E9D6 60%, #F4E3CC 100%)',
        'gradient-tasting': 'linear-gradient(135deg, #FEF3E7 0%, #F7F3EA 100%)',
        'gradient-warm': 'linear-gradient(135deg, #FEF3E7 0%, #FCE4C8 50%, #F8C794 100%)',
        // Radial gradient (base only - variants removed as unused)
        'gradient-radial': 'radial-gradient(circle at center, var(--tw-gradient-stops))',
      },
      backdropBlur: {
        none: '0',
        sm: '4px',
        DEFAULT: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        '2xl': '40px',
        '3xl': '64px',
      },
      blur: {
        none: '0',
        sm: '4px',
        DEFAULT: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        '2xl': '40px',
        '3xl': '64px',
      },
      minHeight: {
        'touch': '44px',
        'touch-large': '48px',
        'touch-xl': '52px',
        0: '0px',
        full: '100vh',
        screen: '100vh',
        'safe-screen': 'calc(100vh - env(safe-area-inset-top) - env(safe-area-inset-bottom))',
      },
      animation: {
        none: 'none',
        spin: 'spin 1s linear infinite',
        ping: 'ping 1s cubic-bezier(0, 0, 0.2, 1) infinite',
        pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        bounce: 'bounce 1s infinite',
        // Custom animations
        'fade-in': 'fadeIn 0.3s ease-in-out',
        'fade-out': 'fadeOut 0.3s ease-in-out',
        'fade-in-up': 'fadeInUp 0.5s ease-out',
        'slide-in-up': 'slideInUp 0.3s ease-out',
        'slide-in-down': 'slideInDown 0.3s ease-out',
        'slide-in-left': 'slideInLeft 0.3s ease-out',
        'slide-in-right': 'slideInRight 0.3s ease-out',
        'slide-up': 'slideUp 0.4s ease-out forwards',
        'scale-out': 'scaleOut 0.3s ease-in',
        'shimmer': 'shimmer 2s linear infinite',
        'checkmark-pulse': 'checkmarkPulse 0.6s ease-out',
        'shake': 'shake 0.3s ease-in-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeOut: {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        slideInUp: {
          '0%': { transform: 'translateY(100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideInDown: {
          '0%': { transform: 'translateY(-100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideInLeft: {
          '0%': { transform: 'translateX(-100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideInRight: {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        scaleOut: {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '100%': { transform: 'scale(0.9)', opacity: '0' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        checkmarkPulse: {
          '0%': { transform: 'scale(0)', opacity: '0' },
          '50%': { transform: 'scale(1.2)', opacity: '1' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '25%': { transform: 'translateX(-4px)' },
          '75%': { transform: 'translateX(4px)' },
        },
      },
      transitionDuration: {
        DEFAULT: '150ms',
      },
      transitionTimingFunction: {
        DEFAULT: 'cubic-bezier(0, 0, 0.2, 1)',
      },
      screens: {
        'xs': '375px',
        'mobile': '0px',
        'tablet': '640px',
        'desktop': '1024px',
        'wide': '1280px',
        'ultra': '1536px',
        // Custom breakpoints
        'touch': { 'raw': '(hover: none) and (pointer: coarse)' },
        'hover': { 'raw': '(hover: hover) and (pointer: fine)' },
        'reduced-motion': { 'raw': '(prefers-reduced-motion: reduce)' },
        // Mobile-specific breakpoints
        'sm-mobile': '320px',
        'md-mobile': '375px',
        'lg-mobile': '414px',
      },
      aria: {
        busy: 'busy="true"',
        checked: 'checked="true"',
        disabled: 'disabled="true"',
        expanded: 'expanded="true"',
        hidden: 'hidden="true"',
        pressed: 'pressed="true"',
        readonly: 'readonly="true"',
        required: 'required="true"',
        selected: 'selected="true"',
      },
    },
  },
  plugins: [],
}